### PR TITLE
MHUB-31: Add IconScout license

### PR DESCRIPTION
**Pull request by thudon-coveo**
[The license](https://iconscout.com/licenses#simple_license)

Need this license for https://github.com/Iconscout/react-unicons

### CODE REVIEW

**Review by Mblanchetdeverly — CHANGES_REQUESTED** [review]
@thudon-coveo I'm not confortable adding this license in the approved list for distributed projects as the license is unclear and seems to indicate that redistribution is not permitted.  I could however approve it for your specific use-case if you confirm that the files will be used as-is and not modified.

**Comment by thudon-coveo** [comment]
> @thudon-coveo I'm not confortable adding this license in the approved list for distributed projects as the license is unclear and seems to indicate that redistribution is not permitted. I could however approve it for your specific use-case if you confirm that the files will be used as-is and not modified.

What do you mean by `as-is`. We wouldn't do something like changing the code that's for sure. But we might change the colour/size of the icons when using them.

**Comment by Mblanchetdeverly** [comment]
> > @thudon-coveo I'm not confortable adding this license in the approved list for distributed projects as the license is unclear and seems to indicate that redistribution is not permitted. I could however approve it for your specific use-case if you confirm that the files will be used as-is and not modified.
> 
> What do you mean by `as-is`. We wouldn't do something like changing the code that's for sure. But we might change the colour/size of the icons when using them.

That's fine, licence is approved for that use-case.

**Comment by thudon-coveo** [comment]
> > > @thudon-coveo I'm not confortable adding this license in the approved list for distributed projects as the license is unclear and seems to indicate that redistribution is not permitted. I could however approve it for your specific use-case if you confirm that the files will be used as-is and not modified.
> > 
> > 
> > What do you mean by `as-is`. We wouldn't do something like changing the code that's for sure. But we might change the colour/size of the icons when using them.
> 
> That's fine, licence is approved for that use-case.

Good news that's all we're planning to do 🚀 

Could you approve the PR 😃 ?

**Comment by samuelfullerthomas** [comment]
I think the license is saying:

> Modifications to Files are deemed derivative works and can be used for commercial as well as personal projects but [the files (aka IconScout)] are not allowed to [be resold or republished] ( as a separate entity under any other profile) to any platform.

which tracks as on the about page the license is summed up as:

Screenshot 2023-08-16 at 10 51 52

**Comment by Mblanchetdeverly** [comment]
> I think the license is saying:
> 
> > Modifications to Files are deemed derivative works and can be used for commercial as well as personal projects but [the files (aka IconScout)] are not allowed to [be resold or republished] ( as a separate entity under any other profile) to any platform.
> 
> which tracks as on the about page the license is summed up as:
> 
> Screenshot 2023-08-16 at 10 51 52
> 
> So we can't resell iconscout, but we are free to use it as we see fit.

You can't resell OR republish, which can be interpreted broadly - I've been reading about the license and the phrasing is just too unclear for me to allow the license at large for all our distributed projects. As I explained to Tommy, feel free to use iconscount nonetheless for your specific use case, by ignoring the flag that is raised by Github with a comment that legal approved it. Is that possible? Thanks

**Comment by thudon-coveo** [comment]
> > I think the license is saying:
> > > Modifications to Files are deemed derivative works and can be used for commercial as well as personal projects but [the files (aka IconScout)] are not allowed to [be resold or republished] ( as a separate entity under any other profile) to any platform.
> > 
> > 
> > which tracks as on the about page the license is summed up as:
> > Screenshot 2023-08-16 at 10 51 52
> > So we can't resell iconscout, but we are free to use it as we see fit.
> 
> You can't resell OR republish, which can be interpreted broadly - I've been reading about the license and the phrasing is just too unclear for me to allow the license at large for all our distributed projects. As I explained to Tommy, feel free to use iconscount nonetheless for your specific use case, by ignoring the flag that is raised by Github with a comment that legal approved it. Is that possible? Thanks

Yes that's what we did. Thanks @Mblanchetdeverly

**Pull request closed without merging**
